#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

_mpl_dir = Path(tempfile.gettempdir()) / f"matplotlib_{os.getuid()}"
_mpl_dir.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_mpl_dir))

import matplotlib.pyplot as plt
from matplotlib.colors import to_rgba
import numpy as np
import pandas as pd

try:
    from .clip_groove_fluctuation_direction import DEFAULT_CONTACTS_TSV, OUT_DIR, ROOT
except ImportError:  # pragma: no cover - supports direct script execution
    from clip_groove_fluctuation_direction import DEFAULT_CONTACTS_TSV, OUT_DIR, ROOT

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from features import explore_features as featmap


DEFAULT_OUT_PDF = OUT_DIR / "clip_core_rank001_contact_probabilities.pdf"
DEFAULT_OUT_TSV = OUT_DIR / "clip_core_rank001_contact_probability_summary.tsv"
DEFAULT_ALPHA_REF = featmap.DEFAULT_ALPHA_REF
DEFAULT_BETA_REF = featmap.DEFAULT_BETA_REF
DEFAULT_ENERGY_ROOT = ROOT
CLIP_RANK001_CONTACTS = OUT_DIR / "clip_core_rank001_direct_contacts.tsv"
CLIP_RANK1000_CONTACTS = OUT_DIR / "clip_core_rank1000_direct_contacts.tsv"
CLIP_HIGH_RANK_START = 901
CLIP_HIGH_RANK_END = 1000
CLIP_HIGH_RANK_CONTACTS = OUT_DIR / "clip_core_highrank901_1000_direct_contacts.tsv"
ALPHA_BETA_RANK001_CONTACTS = OUT_DIR / "alpha_beta_rank001_direct_contacts.tsv"
ALPHA_BETA_RANK1000_CONTACTS = OUT_DIR / "alpha_beta_rank1000_direct_contacts.tsv"
CLIP_RANK001_SUMMARY = OUT_DIR / "clip_core_rank001_contact_probability_summary.tsv"
CLIP_RANK1000_SUMMARY = OUT_DIR / "clip_core_rank1000_contact_probability_summary.tsv"
CLIP_HIGH_RANK_SUMMARY = OUT_DIR / "clip_core_highrank901_1000_contact_probability_summary.tsv"
ALPHA_BETA_RANK001_SUMMARY = OUT_DIR / "alpha_beta_rank001_contact_probability_summary.tsv"
ALPHA_BETA_RANK1000_SUMMARY = OUT_DIR / "alpha_beta_rank1000_contact_probability_summary.tsv"

# X-tick font sizes for every panel in the standard PDFs generated by
# `python plot_clip_core_contact_probabilities.py`.
#
# Each PDF has two panels: alpha-chain contacts on the left and beta-chain
# contacts on the right. Edit these values to tune each panel independently.
XTICK_FONTSIZE_CLIP_RANK001_ALPHA = 22
XTICK_FONTSIZE_CLIP_RANK001_BETA = 23

XTICK_FONTSIZE_CLIP_HIGH_RANK_ALPHA = 14.5
XTICK_FONTSIZE_CLIP_HIGH_RANK_BETA = 12.5

XTICK_FONTSIZE_AB_RANK001_FULL_ALPHA = 20
XTICK_FONTSIZE_AB_RANK001_FULL_BETA = 20

XTICK_FONTSIZE_AB_RANK1000_FULL_ALPHA = 20
XTICK_FONTSIZE_AB_RANK1000_FULL_BETA = 20

XTICK_FONTSIZE_AB_RANK001_SUB100_ALPHA = 20
XTICK_FONTSIZE_AB_RANK001_SUB100_BETA = 20

XTICK_FONTSIZE_AB_RANK1000_SUB100_ALPHA = 20
XTICK_FONTSIZE_AB_RANK1000_SUB100_BETA = 20

# Fallbacks for custom command-line calls with non-standard output names.
XTICK_FONTSIZE_ALPHA_CLIP = XTICK_FONTSIZE_CLIP_RANK001_ALPHA
XTICK_FONTSIZE_BETA_CLIP = XTICK_FONTSIZE_CLIP_RANK001_BETA
XTICK_FONTSIZE_ALPHA_CORE = XTICK_FONTSIZE_AB_RANK001_FULL_ALPHA
XTICK_FONTSIZE_BETA_CORE = XTICK_FONTSIZE_AB_RANK001_FULL_BETA

# Wider canvas for alpha/beta scaffold maps because they contain many more residues.
FIGSIZE_CLIP_CORE = (18.0, 6.2)
FIGSIZE_ALPHA_BETA_CORE = (28.0, 6.2)

# Half-interval padding around the first and last residue tick. Lower values
# use more of the canvas for tick spacing, but values below ~0.40 may clip bars.
X_AXIS_EDGE_PADDING = 0.45

# Shared signed energy axis for alpha/beta core residue-energy panels.
ENERGY_TOTAL_YLIM = (-4.0, 4.0)

CONTACT_PROBABILITY_BAR_COLOR = "green"
UNCOMMON_XTICK_COLOR_ALPHA = "red"
UNCOMMON_XTICK_COLOR_BETA = "blue"
SUB100_BAR_COLOR_ALPHA = "red"
SUB100_BAR_COLOR_BETA = "blue"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot rank-001 alpha/beta CLIP-core contact probabilities."
    )
    parser.add_argument("--contacts-tsv", type=Path, default=DEFAULT_CONTACTS_TSV)
    parser.add_argument("--out-pdf", type=Path, default=DEFAULT_OUT_PDF)
    parser.add_argument("--out-tsv", type=Path, default=DEFAULT_OUT_TSV)
    parser.add_argument("--alpha-ref", type=Path, default=DEFAULT_ALPHA_REF)
    parser.add_argument("--beta-ref", type=Path, default=DEFAULT_BETA_REF)
    parser.add_argument(
        "--energy-total-tsv",
        type=Path,
        default=None,
        help=(
            "Optional precomputed signed energy_total summary. If omitted, "
            "alpha/beta-core plots compute rank-specific values from "
            "*_Repair_residue_values.tsv files."
        ),
    )
    parser.add_argument(
        "--energy-root",
        type=Path,
        default=DEFAULT_ENERGY_ROOT,
        help="Root containing X.Y/X.Y_Z.W/X.Y_Z.W_results directories for signed energy_total lookup.",
    )
    parser.add_argument(
        "--require-complete-alpha-panel",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Keep only alpha-parent panels with the modal number of beta combinations.",
    )
    parser.add_argument(
        "--alpha-beta-contact-subset",
        choices=("full", "sub100"),
        default="full",
        help=(
            "For alpha/beta-core plots, show either 100%% preserved contacts "
            "('full') or contacts present in <100%% of heterodimers ('sub100')."
        ),
    )
    return parser.parse_args()


def parse_source_resnum(value: object) -> int | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        return int(float(text))
    except Exception:
        return None


def filter_to_complete_panel(df: pd.DataFrame) -> pd.DataFrame:
    pairs = df[["heterodimer"]].drop_duplicates().copy()
    pairs["alpha_code"] = pairs["heterodimer"].str.split("_").str[0]
    counts = pairs.groupby("alpha_code")["heterodimer"].nunique()
    modal_count = int(counts.mode().iloc[0])
    keep_alpha = set(counts[counts == modal_count].index)
    return df[df["heterodimer"].str.split("_").str[0].isin(keep_alpha)].copy()


def map_contacts_to_consensus_axis(
    df: pd.DataFrame,
    alpha_ref: featmap.ChainReference,
    beta_ref: featmap.ChainReference,
) -> pd.DataFrame:
    """Map allele-specific PDB residue numbers onto the shared MSA axes."""
    mapped_parts: list[pd.DataFrame] = []
    failed = 0

    for heterodimer, hdf in df.groupby("heterodimer", sort=False):
        het = featmap.parse_heterodimer_codes(str(heterodimer), alpha_ref, beta_ref)
        for chain_label, allele_code, ref in (
            ("alpha", het.alpha, alpha_ref),
            ("beta", het.beta, beta_ref),
        ):
            sub = hdf.loc[hdf["chain_label"] == chain_label].copy()
            if sub.empty:
                continue

            seq = ref.allele_sequences[allele_code].copy()
            seq["source_resnum"] = seq["source_resnum"].astype(int)
            lookup = seq.set_index("source_resnum")[
                ["msa_resnum", "sort_value", "aa", "axis_label"]
            ]

            sub["source_resnum"] = sub["residue_id"].map(parse_source_resnum)
            sub = sub.dropna(subset=["source_resnum"]).copy()
            sub["source_resnum"] = sub["source_resnum"].astype(int)

            mapped = sub.join(lookup, on="source_resnum", how="left")
            failed += int(mapped["msa_resnum"].isna().sum())
            mapped = mapped.dropna(subset=["msa_resnum", "sort_value"]).copy()
            mapped["msa_resnum"] = mapped["msa_resnum"].astype(str)
            mapped["axis_label"] = mapped["axis_label"].astype(str)
            mapped_parts.append(mapped)

    if not mapped_parts:
        raise SystemExit("No contact rows could be mapped to the consensus residue axis.")

    out = pd.concat(mapped_parts, ignore_index=True)
    if failed:
        print(f"[warn] skipped {failed} contact row(s) that did not map to the consensus axis")
    return out


def summarize_contacts(df: pd.DataFrame) -> pd.DataFrame:
    n_heterodimers = df["heterodimer"].nunique()
    observation_cols = ["heterodimer"]
    if "rank" in df.columns:
        observation_cols.append("rank")
    total_observations = df[observation_cols].drop_duplicates().shape[0]
    grouped = (
        df.groupby(["chain_label", "msa_resnum", "axis_label", "sort_value"], as_index=False)
        .agg(
            n_heterodimers=("heterodimer", "nunique"),
            n_contact_observations=("heterodimer", "size"),
            source_residue_ids=("source_resnum", lambda x: "/".join(map(str, sorted(set(map(int, x)))))),
            residue_letters=("residue_one_letter", lambda x: "/".join(sorted(set(map(str, x))))),
            residue_names=("residue_name", lambda x: "/".join(sorted(set(map(str, x))))),
            median_min_distance_angstrom=("min_distance_angstrom", "median"),
            q25_min_distance_angstrom=("min_distance_angstrom", lambda x: x.quantile(0.25)),
            q75_min_distance_angstrom=("min_distance_angstrom", lambda x: x.quantile(0.75)),
        )
        .sort_values(["chain_label", "sort_value"])
    )
    grouped["n_total_heterodimers"] = n_heterodimers
    grouped["n_total_observations"] = total_observations
    grouped["contact_probability"] = grouped["n_contact_observations"] / total_observations
    grouped["residue_sort"] = grouped["sort_value"]
    return grouped.sort_values(["chain_label", "residue_sort"])


def rank_tag(rank: int) -> str:
    return f"rank_{rank:03d}" if rank < 1000 else f"rank_{rank}"


def single_rank(df: pd.DataFrame) -> int:
    ranks = sorted(pd.to_numeric(df["rank"], errors="coerce").dropna().astype(int).unique())
    if len(ranks) != 1:
        raise SystemExit(f"Expected exactly one rank in contact TSV, found: {ranks}")
    return int(ranks[0])


def rank_values(df: pd.DataFrame) -> list[int]:
    if "rank" not in df.columns:
        return []
    return sorted(pd.to_numeric(df["rank"], errors="coerce").dropna().astype(int).unique())


def interface_values_path(root: Path, heterodimer: str, reference_pdb: str) -> Path:
    alpha_code = heterodimer.split("_", 1)[0]
    results_dir = root / alpha_code / heterodimer / f"{heterodimer}_results"
    if reference_pdb.endswith("_Repair_chained.pdb"):
        filename = reference_pdb.replace("_Repair_chained.pdb", "_Repair_residue_values.tsv")
    else:
        filename = reference_pdb.replace(".pdb", "_residue_values.tsv")
    return results_dir / filename


def read_residue_values(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, sep="\t", comment="#")


def has_usable_energy_rows(df: pd.DataFrame) -> bool:
    needed = {"resname", "chain", "resnum", "total"}
    if not needed.issubset(df.columns):
        return False
    sub = df[list(needed)].copy()
    sub["chain"] = sub["chain"].astype(str).str.upper()
    sub = sub[sub["chain"].isin(["A", "B"])]
    sub["resnum"] = pd.to_numeric(sub["resnum"], errors="coerce")
    sub["total"] = pd.to_numeric(sub["total"], errors="coerce")
    sub = sub.dropna(subset=["resnum", "total", "resname"])
    return not sub.empty


def load_residue_values_with_fallback(path: Path) -> tuple[pd.DataFrame | None, Path | None, bool]:
    """Load residue energy rows, falling back to a non-empty re-repaired file if needed."""
    if path.exists():
        df = read_residue_values(path)
        if has_usable_energy_rows(df):
            return df, path, False

    fallback = path.with_name(path.name.replace("_Repair_residue_values.tsv", "_Repair_Repair_residue_values.tsv"))
    if fallback != path and fallback.exists():
        df = read_residue_values(fallback)
        if has_usable_energy_rows(df):
            return df, fallback, True

    return None, None, False


def standardize_energy_total_table(df: pd.DataFrame, source: str) -> pd.DataFrame:
    df = df.copy()
    if {"energy_total_median", "energy_total_q1", "energy_total_q3"}.issubset(df.columns):
        pass
    elif {"energy_total_median", "energy_total_min", "energy_total_max"}.issubset(df.columns):
        df = df.rename(columns={"energy_total_min": "energy_total_q1", "energy_total_max": "energy_total_q3"})
    else:
        raise SystemExit(
            f"{source} must contain signed energy_total_median with either "
            "energy_total_q1/energy_total_q3 or energy_total_min/energy_total_max."
        )

    required = {"chain", "resnum", "energy_total_median", "energy_total_q1", "energy_total_q3"}
    missing = required - set(df.columns)
    if missing:
        raise SystemExit(f"Missing column(s) in {source}: {sorted(missing)}")

    df["chain"] = df["chain"].astype(str).str.upper()
    df["resnum"] = pd.to_numeric(df["resnum"], errors="coerce").astype("Int64")
    for col in ("energy_total_median", "energy_total_q1", "energy_total_q3"):
        df[col] = pd.to_numeric(df[col], errors="coerce")
    return df.dropna(subset=["chain", "resnum", "energy_total_median"])


def load_energy_total_table(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise SystemExit(f"Missing residue-level energy_total TSV: {path}")
    df = pd.read_csv(path, sep="\t")
    return standardize_energy_total_table(df, str(path))


def compute_rank_energy_total_table(root: Path, contact_df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate signed per-residue energy_total for the same rank and heterodimers as the contact TSV."""
    rank = single_rank(contact_df)
    rows: list[pd.DataFrame] = []
    missing: list[str] = []
    fallback_used: list[str] = []

    for heterodimer, hdf in contact_df.groupby("heterodimer", sort=False):
        refs = hdf["reference_pdb"].dropna().astype(str).unique()
        if len(refs) == 0:
            missing.append(heterodimer)
            continue
        path = interface_values_path(root, str(heterodimer), refs[0])
        loaded = load_residue_values_with_fallback(path)
        df, used_path, used_fallback = loaded
        if df is None or used_path is None:
            missing.append(str(heterodimer))
            continue
        if used_fallback:
            fallback_used.append(str(heterodimer))
        needed = {"resname", "chain", "resnum", "total"}
        if not needed.issubset(df.columns):
            continue
        df = df[list(needed)].copy()
        df["chain"] = df["chain"].astype(str).str.upper()
        df = df[df["chain"].isin(["A", "B"])]
        df["resnum"] = pd.to_numeric(df["resnum"], errors="coerce")
        df["total"] = pd.to_numeric(df["total"], errors="coerce")
        df = df.dropna(subset=["resnum", "total", "resname"])
        df["resnum"] = df["resnum"].astype(int)
        # Files can contain repeated identical residue rows; use one median value per residue per heterodimer.
        df = (
            df.groupby(["chain", "resnum", "resname"], as_index=False)["total"]
            .median()
            .rename(columns={"total": "energy_total"})
        )
        df["heterodimer"] = str(heterodimer)
        rows.append(df)

    if not rows:
        raise SystemExit(f"No signed energy_total rows found for rank {rank} under {root}")

    all_rows = pd.concat(rows, ignore_index=True)
    out = (
        all_rows.groupby(["chain", "resnum"], as_index=False)
        .agg(
            energy_total_median=("energy_total", "median"),
            energy_total_q1=("energy_total", lambda x: x.quantile(0.25)),
            energy_total_q3=("energy_total", lambda x: x.quantile(0.75)),
            energy_total_n=("energy_total", "size"),
            resnames=("resname", lambda x: "/".join(sorted(set(map(str, x))))),
        )
        .sort_values(["chain", "resnum"])
    )
    if missing:
        print(f"[warn] missing signed energy_total files for {len(missing)} heterodimer(s): {', '.join(missing[:10])}")
    if fallback_used:
        print(
            "[warn] used non-empty *_Repair_Repair_residue_values.tsv fallback for "
            f"{len(fallback_used)} heterodimer(s): {', '.join(fallback_used[:10])}"
        )
    print(f"[energy-total] rank={rank} heterodimers={all_rows['heterodimer'].nunique()} residues={len(out)}")
    return out


def add_energy_total(summary: pd.DataFrame, energy_total: pd.DataFrame) -> pd.DataFrame:
    """Attach residue-level energy_total using the same chain/residue numbering as plot_penalties.py."""
    energy_lookup = energy_total.set_index(["chain", "resnum"])

    def lookup_energy(row: pd.Series, col: str) -> float:
        chain = "A" if row["chain_label"] == "alpha" else "B"
        values = []
        for text in str(row["source_residue_ids"]).split("/"):
            try:
                key = (chain, int(float(text)))
            except ValueError:
                continue
            if key in energy_lookup.index:
                values.append(float(energy_lookup.loc[key, col]))
        return float(np.nanmedian(values)) if values else np.nan

    out = summary.copy()
    out["energy_total_median"] = out.apply(lambda row: lookup_energy(row, "energy_total_median"), axis=1)
    out["energy_total_q1"] = out.apply(lambda row: lookup_energy(row, "energy_total_q1"), axis=1)
    out["energy_total_q3"] = out.apply(lambda row: lookup_energy(row, "energy_total_q3"), axis=1)
    return out


def contact_labels_by_chain(summary: pd.DataFrame, contact_subset: str) -> dict[str, set[str]]:
    out: dict[str, set[str]] = {"alpha": set(), "beta": set()}
    if contact_subset == "full":
        sub = summary[summary["contact_probability"] >= 0.999999]
    elif contact_subset == "sub100":
        sub = summary[summary["contact_probability"] < 0.999999]
    else:
        sub = summary
    for chain_label, cdf in sub.groupby("chain_label"):
        out[str(chain_label)] = set(cdf["axis_label"].astype(str))
    return out


def rank_comparison_summary_path(contact_mode: str, rank: int) -> Path | None:
    if contact_mode == "clip_core":
        if rank == 1:
            return CLIP_HIGH_RANK_SUMMARY
        if rank == 1000:
            return CLIP_RANK001_SUMMARY
        return None
    if rank == 1:
        return ALPHA_BETA_RANK1000_SUMMARY
    if rank == 1000:
        return ALPHA_BETA_RANK001_SUMMARY
    return None


def noncommon_contact_labels(
    summary: pd.DataFrame,
    contact_df: pd.DataFrame,
    contact_mode: str,
    alpha_beta_contact_subset: str,
) -> dict[str, set[str]]:
    """Return plotted contact labels present in this rank but absent in the paired rank."""
    ranks = rank_values(contact_df)
    if contact_mode == "clip_core" and ranks == list(range(CLIP_HIGH_RANK_START, CLIP_HIGH_RANK_END + 1)):
        other_path = CLIP_RANK001_SUMMARY
    elif contact_mode == "clip_core" and ranks == [1]:
        other_path = CLIP_HIGH_RANK_SUMMARY
    elif contact_mode == "clip_core" and len(ranks) != 1:
        return {"alpha": set(), "beta": set()}
    else:
        rank = single_rank(contact_df)
        other_path = rank_comparison_summary_path(contact_mode, rank)
    if other_path is None or not other_path.exists():
        return {"alpha": set(), "beta": set()}

    contact_subset = alpha_beta_contact_subset if contact_mode == "alpha_beta_core" else "all"
    current = contact_labels_by_chain(summary, contact_subset=contact_subset)
    other = contact_labels_by_chain(pd.read_csv(other_path, sep="\t"), contact_subset=contact_subset)
    return {
        "alpha": current["alpha"] - other.get("alpha", set()),
        "beta": current["beta"] - other.get("beta", set()),
    }


def tick_label(axis_label: object) -> str:
    """Use the compact consensus-axis label style used by explore_features.py."""
    return str(axis_label)


def infer_contact_mode(df: pd.DataFrame) -> str:
    return "alpha_beta_core" if "target_chain_label" in df.columns else "clip_core"


def xtick_fontsize(contact_mode: str, chain_label: str) -> int:
    if contact_mode == "alpha_beta_core":
        return XTICK_FONTSIZE_ALPHA_CORE if chain_label == "alpha" else XTICK_FONTSIZE_BETA_CORE
    return XTICK_FONTSIZE_ALPHA_CLIP if chain_label == "alpha" else XTICK_FONTSIZE_BETA_CLIP


def uncommon_xtick_color(chain_label: str) -> str:
    return UNCOMMON_XTICK_COLOR_ALPHA if chain_label == "alpha" else UNCOMMON_XTICK_COLOR_BETA


def plot_panel(
    ax,
    summary: pd.DataFrame,
    chain_label: str,
    color: str,
    x_tick_fontsize: int,
    bold_labels: set[str] | None = None,
) -> None:
    sub = summary[summary["chain_label"] == chain_label].sort_values("residue_sort")
    x = np.arange(len(sub))
    labels = [tick_label(row.axis_label) for row in sub.itertuples(index=False)]

    ax.bar(
        x,
        sub["contact_probability"],
        color=to_rgba(CONTACT_PROBABILITY_BAR_COLOR, 0.50),
        edgecolor=to_rgba("black", 0.75),
        linewidth=0.45,
    )
    ax.set_ylim(0.0, 1.08)
    ax.set_ylabel("Contact probability")
    chain_symbol = r"$\alpha$" if chain_label == "alpha" else r"$\beta$"
    ax.set_xlabel(f"Consensus residue (chain {chain_symbol})")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=90, ha="center")
    for label in ax.get_xticklabels():
        if bold_labels and label.get_text() in bold_labels:
            label.set_fontweight("bold")
            label.set_color(uncommon_xtick_color(chain_label))
    ax.tick_params(axis="x", labelsize=x_tick_fontsize)
    ax.tick_params(axis="y", labelsize=22)
    if len(x):
        ax.set_xlim(-X_AXIS_EDGE_PADDING, len(x) - 1 + X_AXIS_EDGE_PADDING)
    ax.grid(axis="y", color="black", alpha=0.25, linestyle="--", lw=0.8)

    dist_ax = ax.twinx()
    y = sub["median_min_distance_angstrom"].to_numpy(dtype=float)
    q25 = sub["q25_min_distance_angstrom"].to_numpy(dtype=float)
    q75 = sub["q75_min_distance_angstrom"].to_numpy(dtype=float)
    dist_ax.fill_between(x, q25, q75, color="black", alpha=0.20, linewidth=0)
    dist_ax.plot(
        x,
        y,
        color="black",
        linewidth=1.6,
        marker="o",
        markerfacecolor=to_rgba("black", 0.30),
        markeredgecolor="black",
        markersize=4.5,
    )
    dist_ax.set_ylim(0.0, 5.2)
    dist_ax.set_ylabel("Minimum distance [Å]")
    dist_ax.tick_params(axis="y", labelsize=22)


def plot_core_panel(
    ax,
    summary: pd.DataFrame,
    chain_label: str,
    color: str,
    x_tick_fontsize: int,
    bold_labels: set[str] | None = None,
    contact_subset: str = "full",
) -> None:
    chain_rows = summary[summary["chain_label"] == chain_label]
    if contact_subset == "sub100":
        sub = chain_rows[chain_rows["contact_probability"] < 0.999999].sort_values("residue_sort")
        empty_text = "<100% contact residues"
        xlabel_text = "Consensus residue (<100% contact)"
    else:
        sub = chain_rows[chain_rows["contact_probability"] >= 0.999999].sort_values("residue_sort")
        empty_text = "100% contact residues"
        xlabel_text = "Consensus residue (100% contact)"
    sub = sub.copy()
    if sub.empty:
        ax.text(0.5, 0.5, f"No {empty_text}", ha="center", va="center", transform=ax.transAxes)
        ax.set_axis_off()
        return

    x = np.arange(len(sub))
    labels = [tick_label(row.axis_label) for row in sub.itertuples(index=False)]
    energy = sub["energy_total_median"].to_numpy(dtype=float)

    if contact_subset == "sub100":
        bar_color = SUB100_BAR_COLOR_ALPHA if chain_label == "alpha" else SUB100_BAR_COLOR_BETA
        ax.bar(
            x,
            sub["contact_probability"],
            color=to_rgba(bar_color, 0.50),
            edgecolor=to_rgba("black", 0.50),
            linewidth=0.40,
            zorder=1,
        )

    ax.fill_between(
        x,
        sub["energy_total_q1"],
        sub["energy_total_q3"],
        color="green",
        alpha=0.20,
        linewidth=0,
        zorder=3,
    )
    ax.plot(
        x,
        energy,
        color="green",
        linewidth=1.8,
        marker="o",
        markerfacecolor=to_rgba("green", 0.35),
        markeredgecolor="green",
        markersize=5.0,
        zorder=4,
    )
    ax.axhline(0.0, color="#008000", linestyle="--", lw=2.4, alpha=0.50, zorder=20)
    ax.set_ylabel("Consensus residue total energy [kcal/mol]")
    chain_symbol = r"$\alpha$" if chain_label == "alpha" else r"$\beta$"
    ax.set_xlabel(f"{xlabel_text} (chain {chain_symbol})")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=90, ha="center")
    for label in ax.get_xticklabels():
        if bold_labels and label.get_text() in bold_labels:
            label.set_fontweight("bold")
            label.set_color(uncommon_xtick_color(chain_label))
    ax.tick_params(axis="x", labelsize=x_tick_fontsize)
    ax.tick_params(axis="y", labelsize=22)
    if len(x):
        ax.set_xlim(-X_AXIS_EDGE_PADDING, len(x) - 1 + X_AXIS_EDGE_PADDING)
    ax.set_ylim(*ENERGY_TOTAL_YLIM)
    ax.grid(axis="y", color="black", alpha=0.25, linestyle="--", lw=0.8)

    dist_ax = ax.twinx()
    y = sub["median_min_distance_angstrom"].to_numpy(dtype=float)
    q25 = sub["q25_min_distance_angstrom"].to_numpy(dtype=float)
    q75 = sub["q75_min_distance_angstrom"].to_numpy(dtype=float)
    dist_ax.fill_between(x, q25, q75, color="black", alpha=0.20, linewidth=0)
    dist_ax.plot(
        x,
        y,
        color="black",
        linewidth=1.6,
        marker="o",
        markerfacecolor=to_rgba("black", 0.30),
        markeredgecolor="black",
        markersize=5.0,
    )
    dist_ax.set_ylim(0.0, 5.2)
    dist_ax.set_ylabel("Minimum distance [Å]")
    dist_ax.tick_params(axis="y", labelsize=22)


def plot_figure(
    summary: pd.DataFrame,
    out_pdf: Path,
    contact_mode: str,
    noncommon_labels: dict[str, set[str]] | None = None,
    alpha_beta_contact_subset: str = "full",
    xtick_fontsizes: dict[str, int] | None = None,
) -> None:
    plt.rcParams.update(
        {
            "font.family": "STIXGeneral",
            "mathtext.fontset": "stix",
            "text.usetex": False,
            "font.size": 18,
            "axes.labelsize": 32,
            "xtick.labelsize": 16,
            "ytick.labelsize": 22,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    figsize = FIGSIZE_ALPHA_BETA_CORE if contact_mode == "alpha_beta_core" else FIGSIZE_CLIP_CORE
    fig, axes = plt.subplots(1, 2, figsize=figsize, constrained_layout=True)
    xtick_fontsizes = xtick_fontsizes or {}
    alpha_xtick_fontsize = xtick_fontsizes.get("alpha", xtick_fontsize(contact_mode, "alpha"))
    beta_xtick_fontsize = xtick_fontsizes.get("beta", xtick_fontsize(contact_mode, "beta"))
    if contact_mode == "alpha_beta_core":
        noncommon_labels = noncommon_labels or {"alpha": set(), "beta": set()}
        plot_core_panel(
            axes[0],
            summary,
            "alpha",
            "red",
            alpha_xtick_fontsize,
            noncommon_labels.get("alpha", set()),
            alpha_beta_contact_subset,
        )
        plot_core_panel(
            axes[1],
            summary,
            "beta",
            "blue",
            beta_xtick_fontsize,
            noncommon_labels.get("beta", set()),
            alpha_beta_contact_subset,
        )
    else:
        noncommon_labels = noncommon_labels or {"alpha": set(), "beta": set()}
        plot_panel(
            axes[0],
            summary,
            "alpha",
            "red",
            alpha_xtick_fontsize,
            noncommon_labels.get("alpha", set()),
        )
        plot_panel(
            axes[1],
            summary,
            "beta",
            "blue",
            beta_xtick_fontsize,
            noncommon_labels.get("beta", set()),
        )
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_pdf, bbox_inches="tight")
    plt.close(fig)


def default_plot_jobs() -> list[argparse.Namespace]:
    """Standard figure set generated when the script is run without arguments."""
    shared = {
        "alpha_ref": DEFAULT_ALPHA_REF,
        "beta_ref": DEFAULT_BETA_REF,
        "energy_total_tsv": None,
        "energy_root": DEFAULT_ENERGY_ROOT,
        "require_complete_alpha_panel": True,
    }
    return [
        argparse.Namespace(
            contacts_tsv=CLIP_RANK001_CONTACTS,
            out_pdf=OUT_DIR / "clip_core_rank001_contact_probabilities.pdf",
            out_tsv=CLIP_RANK001_SUMMARY,
            alpha_beta_contact_subset="full",
            xtick_fontsizes={
                "alpha": XTICK_FONTSIZE_CLIP_RANK001_ALPHA,
                "beta": XTICK_FONTSIZE_CLIP_RANK001_BETA,
            },
            **shared,
        ),
        argparse.Namespace(
            contacts_tsv=CLIP_HIGH_RANK_CONTACTS,
            out_pdf=OUT_DIR / "clip_core_highrank901_1000_contact_probabilities.pdf",
            out_tsv=CLIP_HIGH_RANK_SUMMARY,
            alpha_beta_contact_subset="full",
            xtick_fontsizes={
                "alpha": XTICK_FONTSIZE_CLIP_HIGH_RANK_ALPHA,
                "beta": XTICK_FONTSIZE_CLIP_HIGH_RANK_BETA,
            },
            **shared,
        ),
        argparse.Namespace(
            contacts_tsv=ALPHA_BETA_RANK001_CONTACTS,
            out_pdf=OUT_DIR / "alpha_beta_rank001_contact_probabilities.pdf",
            out_tsv=ALPHA_BETA_RANK001_SUMMARY,
            alpha_beta_contact_subset="full",
            xtick_fontsizes={
                "alpha": XTICK_FONTSIZE_AB_RANK001_FULL_ALPHA,
                "beta": XTICK_FONTSIZE_AB_RANK001_FULL_BETA,
            },
            **shared,
        ),
        argparse.Namespace(
            contacts_tsv=ALPHA_BETA_RANK1000_CONTACTS,
            out_pdf=OUT_DIR / "alpha_beta_rank1000_contact_probabilities.pdf",
            out_tsv=ALPHA_BETA_RANK1000_SUMMARY,
            alpha_beta_contact_subset="full",
            xtick_fontsizes={
                "alpha": XTICK_FONTSIZE_AB_RANK1000_FULL_ALPHA,
                "beta": XTICK_FONTSIZE_AB_RANK1000_FULL_BETA,
            },
            **shared,
        ),
        argparse.Namespace(
            contacts_tsv=ALPHA_BETA_RANK001_CONTACTS,
            out_pdf=OUT_DIR / "alpha_beta_rank001_sub100_contact_probabilities.pdf",
            out_tsv=OUT_DIR / "alpha_beta_rank001_sub100_contact_probability_summary.tsv",
            alpha_beta_contact_subset="sub100",
            xtick_fontsizes={
                "alpha": XTICK_FONTSIZE_AB_RANK001_SUB100_ALPHA,
                "beta": XTICK_FONTSIZE_AB_RANK001_SUB100_BETA,
            },
            **shared,
        ),
        argparse.Namespace(
            contacts_tsv=ALPHA_BETA_RANK1000_CONTACTS,
            out_pdf=OUT_DIR / "alpha_beta_rank1000_sub100_contact_probabilities.pdf",
            out_tsv=OUT_DIR / "alpha_beta_rank1000_sub100_contact_probability_summary.tsv",
            alpha_beta_contact_subset="sub100",
            xtick_fontsizes={
                "alpha": XTICK_FONTSIZE_AB_RANK1000_SUB100_ALPHA,
                "beta": XTICK_FONTSIZE_AB_RANK1000_SUB100_BETA,
            },
            **shared,
        ),
    ]


def prepare_summary(
    args: argparse.Namespace,
    alpha_ref: featmap.ChainReference,
    beta_ref: featmap.ChainReference,
) -> tuple[pd.DataFrame, pd.DataFrame, str]:
    if not args.contacts_tsv.exists():
        raise SystemExit(f"Missing contact TSV: {args.contacts_tsv}")
    df = pd.read_csv(args.contacts_tsv, sep="\t")
    contact_mode = infer_contact_mode(df)
    if args.require_complete_alpha_panel:
        df = filter_to_complete_panel(df)
    df = map_contacts_to_consensus_axis(df, alpha_ref, beta_ref)
    summary = summarize_contacts(df)
    if contact_mode == "alpha_beta_core":
        energy_total = (
            load_energy_total_table(args.energy_total_tsv)
            if args.energy_total_tsv is not None
            else compute_rank_energy_total_table(args.energy_root, df)
        )
        summary = add_energy_total(summary, energy_total)
    return summary, df, contact_mode


def write_summary_and_plot(
    args: argparse.Namespace,
    summary: pd.DataFrame,
    mapped_contacts: pd.DataFrame,
    contact_mode: str,
) -> None:
    noncommon_labels: dict[str, set[str]] | None = None
    if contact_mode == "alpha_beta_core":
        noncommon_labels = noncommon_contact_labels(
            summary,
            mapped_contacts,
            contact_mode,
            args.alpha_beta_contact_subset,
        )
    elif contact_mode == "clip_core":
        noncommon_labels = noncommon_contact_labels(
            summary,
            mapped_contacts,
            contact_mode,
            args.alpha_beta_contact_subset,
        )
    args.out_tsv.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(args.out_tsv, sep="\t", index=False)
    plot_figure(
        summary,
        args.out_pdf,
        contact_mode,
        noncommon_labels,
        args.alpha_beta_contact_subset,
        getattr(args, "xtick_fontsizes", None),
    )
    print(f"[write] {args.out_tsv}")
    print(f"[write] {args.out_pdf}")


def run_jobs(jobs: list[argparse.Namespace]) -> None:
    alpha_ref = featmap.load_reference_table(DEFAULT_ALPHA_REF, "A")
    beta_ref = featmap.load_reference_table(DEFAULT_BETA_REF, "B")
    prepared: list[tuple[argparse.Namespace, pd.DataFrame, pd.DataFrame, str]] = []

    # Write every summary first so paired-rank x-tick highlighting is available
    # even when the output directory starts clean.
    for args in jobs:
        summary, mapped_contacts, contact_mode = prepare_summary(args, alpha_ref, beta_ref)
        args.out_tsv.parent.mkdir(parents=True, exist_ok=True)
        summary.to_csv(args.out_tsv, sep="\t", index=False)
        prepared.append((args, summary, mapped_contacts, contact_mode))

    for args, summary, mapped_contacts, contact_mode in prepared:
        write_summary_and_plot(args, summary, mapped_contacts, contact_mode)


def main() -> int:
    if len(sys.argv) == 1:
        run_jobs(default_plot_jobs())
        return 0

    args = parse_args()
    alpha_ref = featmap.load_reference_table(args.alpha_ref, "A")
    beta_ref = featmap.load_reference_table(args.beta_ref, "B")
    summary, mapped_contacts, contact_mode = prepare_summary(args, alpha_ref, beta_ref)
    write_summary_and_plot(args, summary, mapped_contacts, contact_mode)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
